#!/usr/bin/env python3
"""
Fixed pimping questions for 16 procedures that had duplicate entries.
Each question is UNIQUE to that specific operation — no shared questions.
Categories per procedure: embryology, anatomy, blood supply, complication, clinical pearl.
"""

Q5 = {}

# ============================================================
# BREAST
# ============================================================

Q5["Bilateral Mastectomy"] = [
    {"question": "What is the embryologic origin of the mammary ridge, and what remnant explains supernumerary nipples along the milk line?",
     "answer": "The mammary ridge (milk line) forms during week 6 as a bilateral ectodermal thickening from axilla to inguinal region. Normally all tissue regresses except at the 4th intercostal space. Supernumerary nipples (polythelia, 1-5% of population) represent persistent mammary ridge remnants — most commonly found inferior and medial to the normal nipple. True supernumerary breast tissue (polymastia) can develop cancer."},
    {"question": "What are Cooper's ligaments, and how does their division affect reconstruction after bilateral mastectomy?",
     "answer": "Cooper's ligaments are fibrous septa running from the pectoralis fascia through the breast parenchyma to the dermis, providing structural support. During mastectomy, their complete division detaches the breast from the chest wall. In reconstruction, the absence of Cooper's ligaments means the implant or flap lacks natural support, requiring the inframammary fold to be recreated surgically for an aesthetic result."},
    {"question": "What is the internal mammary perforator anatomy relevant to bilateral mastectomy skin flap survival?",
     "answer": "Internal mammary artery perforators emerge through the 1st-5th intercostal spaces, 1-2cm lateral to the sternum. The dominant perforator is typically at the 2nd or 3rd intercostal space. These are the primary blood supply to medial skin flaps. During bilateral mastectomy, both sides depend on these perforators — aggressive medial dissection risks bilateral flap necrosis, especially with a midline sternal skin bridge."},
    {"question": "What is the incidence and management of bilateral hematoma after bilateral mastectomy with immediate reconstruction?",
     "answer": "Hematoma requiring reoperation: 3-6% per side (cumulative bilateral risk: 6-12%). Most occur within 24 hours. Bilateral simultaneous hematoma is rare but catastrophic — can compress both reconstructions. Unlike unilateral mastectomy, bilateral hematomas double the reoperation risk and anesthesia exposure. Drain management is critical: most surgeons leave drains until output is <30mL/24hrs per side."},
    {"question": "What is the NSABP B-32 trial's relevance to bilateral mastectomy patients undergoing sentinel node biopsy?",
     "answer": "NSABP B-32 validated sentinel lymph node biopsy as equivalent to ALND for staging in clinically node-negative patients. For bilateral mastectomy with bilateral cancers, bilateral SLNB is performed. For bilateral mastectomy with unilateral cancer + contralateral prophylactic, SLNB is needed only on the cancer side. The contralateral prophylactic side does NOT need SLNB (occult cancer found in only 1-5% of prophylactic specimens)."}
]

Q5["Nipple-Sparing Mastectomy"] = [
    {"question": "During fetal development, what is the primary mammary bud and how does it relate to the feasibility of nipple-sparing mastectomy?",
     "answer": "The primary mammary bud forms at week 10 as ectodermal invagination into mesenchyme. By week 16, it branches into 15-20 secondary buds that become the lactiferous ducts converging at the nipple. NSM is oncologically feasible because these terminal ducts contain minimal epithelial tissue at the nipple surface — the retroareolar biopsy confirms no tumor tracks along these ducts to the nipple."},
    {"question": "What is the subareolar plexus of Sappey, and why does it determine incision choice for nipple-sparing mastectomy?",
     "answer": "Sappey's plexus is a rich lymphatic network beneath the areola draining all breast quadrants to the axilla. It runs within the dermis and subdermal layer. Incision placement (inframammary fold, lateral radial, or periareolar) must avoid disrupting the dermal blood supply feeding the NAC. The inframammary fold incision preserves the most NAC blood supply (necrosis rate 2-5%) compared to periareolar incisions (necrosis 10-20%)."},
    {"question": "What is the role of ICG angiography in assessing NAC perfusion intraoperatively during nipple-sparing mastectomy?",
     "answer": "Indocyanine green (ICG) fluorescence angiography provides real-time assessment of NAC perfusion after mastectomy flap creation. IV ICG is imaged with near-infrared camera. Areas without fluorescence at 2 minutes indicate poor perfusion. Studies show ICG reduces NAC necrosis rates from 15% to 5% by identifying ischemic tissue for debridement or guiding conversion to skin-sparing mastectomy when NAC is non-viable."},
    {"question": "What is the rate of nipple loss requiring secondary excision, and what is the management algorithm?",
     "answer": "Complete NAC loss requiring debridement: 2-5%. Partial NAC epidermolysis (superficial desquamation): 10-15%, usually heals with local wound care. Management: observe partial thickness loss with moist dressings (most re-epithelialize in 4-6 weeks). Full-thickness necrosis requires debridement and delayed NAC reconstruction (nipple-sharing graft from contralateral side, local flap, or 3D nipple tattooing)."},
    {"question": "What is the oncologic safety data for nipple-sparing mastectomy — what does the largest meta-analysis show?",
     "answer": "De La Cruz 2015 meta-analysis (12 studies, 5600+ patients): local recurrence rate of 2.4% with NSM versus 3.2% for skin-sparing mastectomy at median 38-month follow-up. The NAC recurrence rate was only 0.9%. The key: proper patient selection (tumor >2cm from NAC, negative retroareolar frozen section) makes NSM oncologically equivalent to total mastectomy for appropriately selected patients."}
]

# ============================================================
# ENDOCRINE
# ============================================================

Q5["Total Thyroidectomy"] = [
    {"question": "The ultimobranchial body contributes what cell type to the thyroid, and what malignancy arises from it?",
     "answer": "The ultimobranchial body (from the 4th/5th pharyngeal pouch, neural crest-derived) migrates into the thyroid and differentiates into parafollicular C cells. These cells produce calcitonin. Medullary thyroid carcinoma (MTC) arises from C cells — it accounts for 3-5% of thyroid cancers and can be sporadic (75%) or hereditary (25%, MEN2A/2B). Serum calcitonin is the tumor marker."},
    {"question": "What is the tubercle of Zuckerkandl, and why is it a critical landmark during total thyroidectomy?",
     "answer": "The tubercle of Zuckerkandl is the posterolateral extension of the thyroid lobe, representing the embryologic point of fusion between the median thyroid anlage and the ultimobranchial body. The recurrent laryngeal nerve passes immediately deep to (medial to) this tubercle before entering the larynx. Identifying the tubercle during dissection leads you directly to the RLN — it is the single most reliable anatomic landmark for nerve identification."},
    {"question": "What is the venous drainage pattern of the thyroid that determines ligation sequence during total thyroidectomy?",
     "answer": "Superior thyroid vein (accompanies superior thyroid artery → internal jugular vein), middle thyroid vein (no accompanying artery — drains directly into the IJV laterally, often the first vessel encountered and divided), and inferior thyroid veins (drain to brachiocephalic veins, run anterior to the trachea). The middle thyroid vein must be divided early to mobilize the lobe laterally off the trachea."},
    {"question": "What is thyroid storm, and how do you manage it if triggered perioperatively during total thyroidectomy?",
     "answer": "Thyroid storm is a life-threatening exacerbation of hyperthyroidism (mortality 10-30%). Perioperative triggers: inadequate preoperative preparation, thyroid gland manipulation. Burch-Wartofsky score >45 confirms diagnosis. Treatment order matters: 1) PTU (blocks synthesis AND peripheral T4→T3 conversion), 2) Beta-blocker (propranolol IV), 3) Iodide (Lugol's — MUST give AFTER PTU to avoid worsening), 4) Hydrocortisone (blocks conversion, treats relative adrenal insufficiency), 5) Cooling."},
    {"question": "What is the significance of intraoperative neural monitoring (IONM) loss of signal during total thyroidectomy?",
     "answer": "If IONM signal is lost on the first side (L1 — loss of signal on ipsilateral RLN), the contralateral side should NOT be operated until nerve recovery is confirmed, as bilateral RLN paralysis requires tracheostomy. A staged procedure (complete the contralateral side 2-3 months later after vocal cord function is confirmed by laryngoscopy) is recommended. This 'staged thyroidectomy' protocol reduces bilateral RLN injury from 0.5% to near zero."}
]

Q5["Hemithyroidectomy/Thyroid Lobectomy"] = [
    {"question": "What is the embryologic significance of the pyramidal lobe, and must it be removed during thyroid lobectomy?",
     "answer": "The pyramidal lobe is a remnant of the thyroglossal duct — a superior extension of thyroid tissue from the isthmus toward the hyoid bone, present in 30-60% of patients. During lobectomy for cancer, the pyramidal lobe should be removed with the isthmus (isthmectomy) if it is on the ipsilateral side, as it may harbor thyroid tissue that could recur. In benign disease, it can be left if not connected to the specimen."},
    {"question": "What is the ligament of Berry's relationship to the inferior thyroid artery during thyroid lobectomy, and why is this the 'danger zone'?",
     "answer": "The ligament of Berry anchors the posterior thyroid to the first two tracheal rings. The RLN enters the larynx within millimeters of this ligament. The terminal branches of the inferior thyroid artery also cross the nerve at this point. The 'danger zone' is the last 1cm of dissection freeing the thyroid from the trachea — the surgeon must use a capsular dissection technique, keeping the scalpel on the thyroid capsule to avoid both the nerve and parathyroid blood supply."},
    {"question": "What is the lymphatic drainage of a thyroid lobe that determines the need for prophylactic central neck dissection?",
     "answer": "Primary drainage: level VI central compartment nodes (pretracheal, paratracheal, prelaryngeal/Delphian node). Secondary: lateral jugular chain (levels II-V). The Delphian node sits on the cricothyroid membrane and is a sentinel node — if positive intraoperatively, formal central neck dissection (level VI) should be performed. Prophylactic CND for cN0 papillary thyroid cancer is debated: ATA recommends it for T3-T4 tumors."},
    {"question": "What is the rate of completion thyroidectomy after lobectomy, and what pathologic findings trigger it?",
     "answer": "10-30% of lobectomies require completion thyroidectomy based on final pathology. Triggers: PTC >4cm, aggressive histology (tall cell, hobnail, columnar), multifocal PTC, extrathyroidal extension, positive margins, vascular invasion (follicular thyroid cancer), or lymph node metastases. Completion thyroidectomy should be performed within 6 months of the initial lobectomy to minimize adhesion scarring."},
    {"question": "After thyroid lobectomy, what percentage of patients develop hypothyroidism requiring levothyroxine?",
     "answer": "22-35% of patients become hypothyroid after lobectomy (TSH >4.5), typically within 6-12 months. Risk factors: elevated preoperative anti-TPO antibodies (Hashimoto's thyroiditis), preoperative TSH in upper-normal range (>2.5), and smaller contralateral lobe. All patients need TSH monitoring at 6 weeks, 3 months, 6 months, and annually. Most can be managed with low-dose levothyroxine (25-75 mcg)."}
]

# ============================================================
# COLORECTAL
# ============================================================

Q5["Robotic Sigmoid Colectomy"] = [
    {"question": "What is the embryologic basis for the sigmoid mesocolon's length and mobility, and why does this matter for robotic port placement?",
     "answer": "The sigmoid colon derives from hindgut and retains a long mesentery because it never fuses with the posterior body wall (unlike the ascending colon). This mesenteric redundancy means the sigmoid is mobile — creating a wide range of anatomic positions. Robotic port placement must account for this variability: the camera port is placed at or above the umbilicus, with working ports triangulated toward the left lower quadrant."},
    {"question": "What is the 'medial-to-lateral' dissection plane in robotic sigmoid colectomy, and what retroperitoneal structures must be identified?",
     "answer": "The medial-to-lateral approach starts at the sacral promontory, incising peritoneum to enter the avascular plane between the mesocolon and Gerota's/Toldt's fascia. Structures identified: left ureter (crossing the iliac bifurcation), left gonadal vessels, left common iliac artery, and the hypogastric nerve plexus. The robot's 3D magnification and wristed instruments make identification of the ureter significantly easier than laparoscopic dissection."},
    {"question": "What is the critical vascular pedicle in sigmoid colectomy, and what determines whether to ligate the IMA at its origin versus distally?",
     "answer": "The IMA is the critical pedicle. High ligation (at the aortic origin) provides a longer vascular pedicle for adequate lymph node harvest and proximal reach for a tension-free anastomosis. Low ligation (preserving the left colic artery) maintains better splenic flexure blood supply via the marginal artery. For cancer: high ligation is standard (adequate lymphadenectomy). For diverticular disease: low ligation is acceptable."},
    {"question": "What is the most common cause of anastomotic leak after robotic sigmoid colectomy, and how does ICG fluorescence angiography reduce its incidence?",
     "answer": "Inadequate perfusion to the anastomosis is the primary modifiable risk factor (leak rate: 3-8%). ICG fluorescence angiography (IV ICG + near-infrared camera) visualizes real-time bowel perfusion at the planned transection site. If the demarcation line shows poor perfusion, the transection is moved proximally to well-perfused bowel. Studies show ICG reduces anastomotic leak rates from 7.4% to 2.5% in colorectal surgery."},
    {"question": "What is the role of complete mesocolic excision (CME) in robotic sigmoid colectomy for cancer, and what does the evidence show?",
     "answer": "CME maintains the mesenteric envelope intact (no tears) with central vascular ligation at the IMA origin — analogous to TME for rectal cancer. The robotic platform facilitates the precise sharp dissection required for intact mesocolic planes. Hohenberger's data: CME improved 5-year cancer-specific survival by 15% compared to conventional surgery. The quality of CME correlates with the number of lymph nodes harvested (target: ≥12 nodes)."}
]

# ============================================================
# UROLOGY
# ============================================================

Q5["Radical Cystectomy"] = [
    {"question": "The bladder trigone has a dual embryologic origin — what are the two sources and why does this matter surgically?",
     "answer": "The trigone's superficial layer derives from mesonephric (Wolffian) duct incorporation (mesoderm), while the deep muscle derives from the surrounding urogenital sinus (endoderm). This dual origin explains the trigone's unique smooth muscle arrangement and its fixed position. During radical cystectomy, the trigone is the last structure divided — the ureteral orifices must be identified here for distal ureteral margin frozen sections."},
    {"question": "What is the space of Retzius, and how is it developed during radical cystectomy?",
     "answer": "The retropubic space (of Retzius) lies between the transversalis fascia/pubic symphysis anteriorly and the bladder/prostate posteriorly. It is entered by incising the peritoneum anterior to the bladder. Key structures within: dorsal venous complex (Santorini's plexus), endopelvic fascia, and puboprostatic/pubovesical ligaments. Controlling the dorsal venous complex (running over the prostatic apex) before division prevents the most significant hemorrhage in the operation."},
    {"question": "What is the obturator fossa anatomy, and what nerve must be preserved during the pelvic lymphadenectomy component of radical cystectomy?",
     "answer": "The obturator fossa is bounded by the external iliac vein superiorly, obturator internus laterally, and bladder medially. The obturator nerve (L2-L4) runs along the lateral pelvic wall through this fossa to exit via the obturator foramen. Injury causes thigh adduction weakness. During lymph node dissection, the nerve must be identified on the lateral pelvic sidewall and preserved — it serves as the lateral boundary of the dissection."},
    {"question": "What is the Enhanced Recovery After Cystectomy (ERAS) protocol, and what is its impact on ileus rates?",
     "answer": "ERAS includes: early feeding (POD 0-1 liquid diet), alvimopan (peripheral mu-opioid antagonist for 7 days — reduces ileus by 30%), gum chewing (stimulates GI motility), early ambulation, multimodal analgesia (minimize opioids), and goal-directed fluid therapy. Ileus is the #1 complication of radical cystectomy (20-30%). ERAS protocols reduce mean hospital stay from 10-12 days to 5-7 days and ileus rates from 30% to 12-15%."},
    {"question": "What is the 90-day mortality and major complication rate after radical cystectomy, and what predicts poor outcomes?",
     "answer": "90-day mortality: 5-8% (one of the highest in elective surgery). Major complication rate (Clavien III-V): 25-30%. Predictors: age >80, ASA ≥3, BMI >35, neoadjuvant chemotherapy toxicity, and high comorbidity index. The 'frailty index' is increasingly used for patient selection. High-volume centers (>20 cases/year) have 30-50% lower mortality than low-volume centers — a strong argument for centralization."}
]

Q5["Orchiectomy"] = [
    {"question": "What is the processus vaginalis, and how does its embryologic persistence create a pathway for testicular tumors?",
     "answer": "The processus vaginalis is a peritoneal diverticulum that descends through the inguinal canal with the testis during fetal development. It normally obliterates, leaving the tunica vaginalis around the testis. If patent, it provides a conduit for peritoneal metastasis of testicular tumors (extremely rare but reported). More importantly, the inguinal approach for orchiectomy follows the processus vaginalis tract to the internal ring, allowing en bloc cord removal."},
    {"question": "What is the anatomy of the inguinal canal relevant to radical inguinal orchiectomy, and what layer is the external oblique aponeurosis opened through?",
     "answer": "The inguinal canal runs from the internal ring (transversalis fascia defect at mid-inguinal point) to the external ring (triangular opening in the external oblique aponeurosis above the pubic tubercle). For radical orchiectomy, the external oblique aponeurosis is opened in the direction of its fibers from the external ring laterally. The cord is identified at the pubic tubercle and controlled with a Penrose drain at the internal ring BEFORE mobilizing the testis — early vascular control prevents hematogenous dissemination."},
    {"question": "What is the venous drainage asymmetry of the testes, and why does this explain the predominance of left-sided varicoceles?",
     "answer": "The right testicular vein drains into the IVC at an oblique angle (low pressure). The left testicular vein drains into the left renal vein at a near 90-degree angle (higher pressure, plus compression between the aorta and SMA — 'nutcracker' phenomenon). This asymmetry explains why 90% of varicoceles are left-sided. During orchiectomy, the testicular vein is divided with the cord, but a new left varicocele in a young man should raise suspicion for retroperitoneal pathology compressing the left renal vein."},
    {"question": "What is testicular prosthesis placement, and when is it offered during orchiectomy?",
     "answer": "A silicone testicular prosthesis can be placed in the scrotum at the time of radical orchiectomy or as a delayed procedure. It is offered to all patients (body image, psychological benefit). Complication rate is low: infection (2-3%), malposition/migration (5%), chronic pain (3%). The prosthesis is placed through the same inguinal incision into the dartos pouch. Patient satisfaction rates are >85%. It does NOT interfere with staging, surveillance imaging, or subsequent chemotherapy."},
    {"question": "What is the RPLND template for stage II testicular cancer, and when is primary RPLND preferred over chemotherapy?",
     "answer": "The modified template for right-sided tumors: interaortocaval, precaval, and paracaval nodes. Left-sided: para-aortic and preaortic nodes. Full bilateral template: both sides plus interaortocaval. Primary RPLND is preferred for: stage IIA/IIB pure seminoma after chemo (residual mass), stage IIA NSGCT with normalized markers (avoids chemo toxicity), and teratoma-predominant tumors (chemo-resistant). Nerve-sparing RPLND preserves antegrade ejaculation in >95% of cases."}
]

Q5["Circumcision"] = [
    {"question": "What is the embryologic development of the male urethra, and how does hypospadias relate to circumcision complications?",
     "answer": "The male urethra forms by fusion of the urethral folds (endoderm) along the ventral surface of the genital tubercle, completing by week 14. Incomplete fusion causes hypospadias. Circumcision in patients with undiagnosed hypospadias is contraindicated because the foreskin is needed for future urethroplasty (the preputial inner mucosa is the preferred tissue for urethral reconstruction). Every infant should be examined for meatal position before circumcision."},
    {"question": "What is Buck's fascia, and how does it serve as a barrier during circumcision complications?",
     "answer": "Buck's fascia is a tough layer of deep penile fascia enveloping the corpora cavernosa and corpus spongiosum. It is deep to the dartos layer and superficial to the tunica albuginea. During circumcision, dissection stays superficial to the dartos — Buck's fascia is NOT violated. If bleeding from circumcision is contained to the dartos (superficial), it resolves with pressure. Hemorrhage deep to Buck's fascia can track into the perineum and requires operative exploration."},
    {"question": "What is the dorsal penile nerve block technique, and where exactly is local anesthetic injected for circumcision analgesia?",
     "answer": "The dorsal penile nerve block targets the dorsal nerves of the penis (branches of the pudendal nerve, S2-S4) where they emerge beneath the pubic symphysis deep to Buck's fascia at the 10 and 2 o'clock positions at the base of the penis. Inject 0.5-1mL of plain lidocaine (NO EPINEPHRINE — end artery territory) at each site. A subcutaneous ring block at the base supplements the ventral supply. Buffering with bicarbonate reduces injection pain."},
    {"question": "What is meatal stenosis after circumcision — its incidence, cause, and management?",
     "answer": "Meatal stenosis (5-10% of circumcised boys, rare in uncircumcised) occurs because the foreskin normally protects the urethral meatus from ammoniacal diaper dermatitis. After circumcision, chronic exposure causes meatal inflammation and scarring. Presents with upward-deflected stream, prolonged voiding, or dysuria — often diagnosed years later. Treatment: meatotomy (office procedure, 95% success) or meatoplasty for severe cases."},
    {"question": "What are the Gomco, Mogen, and Plastibell techniques, and what complication is specific to each?",
     "answer": "Gomco clamp: bell protects glans while foreskin is excised with scalpel — risk: glans amputation if bell size is too small or improperly seated. Mogen clamp: flat clamp applied to foreskin after separating adhesions — risk: glans injury on the dorsal surface (highest glans injury rate). Plastibell: plastic ring tied with suture, foreskin necroses and ring falls off in 5-7 days — risk: proximal migration of the ring causing urinary retention, delayed separation/infection. All have equivalent cosmetic outcomes in experienced hands."}
]

Q5["Laparoscopic Hysterectomy"] = [
    {"question": "During Mullerian duct fusion, what anomaly results from incomplete lateral fusion, and how does it affect hysterectomy planning?",
     "answer": "Incomplete lateral fusion produces a bicornuate uterus (partial fusion) or uterus didelphys (complete non-fusion with two separate uterine cavities and cervices). For laparoscopic hysterectomy, these anomalies alter the vascular anatomy — each horn has its own uterine artery supply, and the dissection must account for two cervices in didelphys. Preoperative MRI is essential to map the anatomy and plan the approach for Mullerian anomalies."},
    {"question": "What is the uterine vascular pedicle during laparoscopic hysterectomy, and at what level is the ureter most at risk?",
     "answer": "The uterine artery crosses over the ureter approximately 1.5cm lateral to the internal cervical os ('water under the bridge'). During laparoscopic hysterectomy, the artery is desiccated with a bipolar or vessel-sealing device at the level of the uterine isthmus. The ureter is most at risk at three points: 1) at the uterine artery crossing, 2) during cardinal ligament division, and 3) during colpotomy (vaginal cuff incision) — thermal spread from energy devices is the main mechanism of laparoscopic ureteral injury."},
    {"question": "What is the pararectal and paravesical space anatomy utilized in difficult laparoscopic hysterectomies?",
     "answer": "The pararectal space (Latzko's space) lies between the ureter medially and the internal iliac artery laterally. The paravesical space lies between the bladder medially and the obturator fossa laterally. Developing these avascular spaces in cases of severe endometriosis or post-cesarean adhesions allows safe identification of the ureter and uterine artery from a retroperitoneal approach before dividing any pedicles — this 'ureter-first' technique dramatically reduces the 1-2% ureteral injury rate."},
    {"question": "What is the incidence of port-site hernia after laparoscopic hysterectomy, and which ports require fascial closure?",
     "answer": "Port-site hernia rate: 1-2% (higher with 12mm ports, especially midline umbilical). All ports ≥10mm require fascial closure with a suture-passer device (Carter-Thomason or Endo-Close). Bladeless trocars reduce port-site hernia compared to bladed trocars. Richter's hernia (partial bowel wall incarceration) can present insidiously days to weeks postoperatively with vague abdominal pain — a high index of suspicion is needed."},
    {"question": "What is the role of uterine manipulators in laparoscopic hysterectomy, and when are they contraindicated?",
     "answer": "Uterine manipulators (V-Care, RUMI) antevert the uterus, delineate the vaginal fornix with a colpotomy cup, and maintain pneumoperitoneum during colpotomy. They are essential for exposure and safe colpotomy. Contraindicated in: known or suspected uterine malignancy (risk of tumor dissemination through the endometrial cavity), cervical stenosis preventing insertion, and pregnancy. For malignancy, a vaginal delineator without intrauterine component is used instead."}
]

Q5["Vulvectomy"] = [
    {"question": "The vulva develops from the genital tubercle and labioscrotal folds. What are the homologous structures in male and female external genitalia?",
     "answer": "Genital tubercle → clitoris (female) / glans penis (male). Urethral folds → labia minora / ventral penile shaft. Labioscrotal swellings → labia majora / scrotum. The vestibular bulbs (female) are homologous to the corpus spongiosum (male). Understanding these homologies matters because vulvar carcinoma SCC arises predominantly from keratinized squamous epithelium of the labia majora — the same tissue type as penile SCC."},
    {"question": "What is the inguinofemoral lymph node anatomy critical to radical vulvectomy, and what is Cloquet's node?",
     "answer": "The superficial inguinal nodes (8-10 nodes above the cribriform fascia) receive primary vulvar lymphatic drainage. Deep inguinal nodes (3-5 nodes medial to the femoral vein, below the cribriform fascia) include Cloquet's node (the most cephalad deep inguinal node, at the femoral ring). Cloquet's node is the sentinel to pelvic node involvement — if negative on frozen section, pelvic lymphadenectomy can be omitted (Hacker's principle)."},
    {"question": "What is the blood supply to the vulva, and which vessel's injury causes the most significant bleeding during vulvectomy?",
     "answer": "Internal pudendal artery (main supply — branches: perineal artery, posterior labial arteries, artery of the vestibular bulb, dorsal artery of the clitoris). External pudendal arteries (from femoral — supply labia majora). The pudendal artery branches within the ischioanal fossa (Alcock's canal). The artery of the vestibular bulb is the most commonly injured vessel during vulvectomy — the bulb is an erectile vascular structure that can cause significant hemorrhage if not controlled."},
    {"question": "What is the most significant complication after radical vulvectomy with bilateral inguinofemoral lymphadenectomy?",
     "answer": "Wound breakdown/dehiscence (30-60%) — the highest wound complication rate of any oncologic procedure. This is because the groin incisions overlie a mobile, moist, bacteria-rich area with poor vascularity after node dissection. The triple-incision technique (separate vulvar and bilateral groin incisions via skin bridges) reduced wound breakdown from 60-80% (en bloc 'butterfly' incision) to 30-40%. Chronic lymphedema of the lower extremities occurs in 30-50%."},
    {"question": "What is the role of sentinel lymph node biopsy in vulvar cancer, and what does the GROINSS-V study show?",
     "answer": "GROINSS-V (2008) and GROINSS-VI (2016): for unifocal vulvar SCC <4cm, sentinel lymph node biopsy with ultrastaging (serial sections + immunohistochemistry) safely replaces complete inguinofemoral lymphadenectomy when the SLN is negative. Groin recurrence rate with negative SLN: 2.3% (comparable to full dissection). SLN biopsy reduces lymphedema from 25-30% to 2%, and wound complications from 30-40% to 12%. This is now the standard for early-stage vulvar cancer."}
]

# ============================================================
# UROLOGY (continued)
# ============================================================

Q5["Lipoma Excision"] = [
    {"question": "What is the embryologic origin of adipose tissue, and why do lipomas have a distinct karyotypic abnormality?",
     "answer": "Adipose tissue derives from mesenchymal stem cells (mesoderm) that differentiate into pre-adipocytes. Lipomas arise from clonal expansion of a single abnormal adipocyte. The most common cytogenetic alteration is translocation or rearrangement at 12q13-15, involving the HMGA2 gene (a chromatin architectural protein). This distinguishes true lipomas from simple fatty deposits — it's a neoplasm, not just excess fat, which is why they recur if the capsule is not completely excised."},
    {"question": "What is the fibrous capsule of a lipoma, and what defines the 'capsular dissection plane' used during excision?",
     "answer": "The lipoma capsule is a thin layer of compressed fibrous tissue formed at the interface between the expanding adipose tumor and surrounding normal fat. The surgical plane is immediately on the capsule surface — sharp or blunt dissection separates the capsule from surrounding tissue. Staying directly on the capsule avoids bleeding from perforating vessels in the surrounding tissue. For the 'squeeze technique' (enucleation), a skin incision smaller than the lipoma allows digital expression through the capsule plane."},
    {"question": "What is the blood supply pattern difference between superficial (subcutaneous) and deep (subfascial/intramuscular) lipomas?",
     "answer": "Superficial lipomas: minimal vascularity, receiving tiny capsular perforators from the subdermal plexus. They can be excised with almost no bleeding. Deep lipomas (subfascial, intramuscular, or retroperitoneal): receive muscular perforators from named regional arteries, develop feeding vessels proportional to their size, and can bleed significantly. Intramuscular lipomas infiltrate between muscle fibers, making capsular dissection incomplete — recurrence rate is 20% versus 1-3% for superficial lipomas."},
    {"question": "What imaging features differentiate a benign lipoma from a well-differentiated liposarcoma (atypical lipomatous tumor)?",
     "answer": "MRI is the gold standard. Benign lipoma: homogeneous high T1 signal (fat), uniform suppression on fat-sat sequences, thin capsule, no enhancement. ALT/WD liposarcoma: thick (>2mm) irregular septations, non-adipose nodular components, enhancement of septa or nodules. Size >10cm, deep location, and any non-fatty component on MRI mandate core needle biopsy before excision. MDM2 amplification on FISH testing confirms the diagnosis of ALT/WD liposarcoma."},
    {"question": "What is Dercum's disease, and how does it change the surgical approach to lipoma excision?",
     "answer": "Dercum's disease (adiposis dolorosa) is a rare syndrome of multiple painful lipomas, predominantly in obese postmenopausal women, associated with depression, fatigue, and cognitive dysfunction. The lipomas are more vascular and inflamed than typical lipomas, making excision bloodier. Surgical excision provides pain relief in 80% of cases, but new lipomas often recur nearby. Liposuction is an alternative for diffuse disease. Familial multiple lipomatosis (autosomal dominant) is a separate entity with painless lipomas."}
]

# ============================================================
# THORACIC
# ============================================================

Q5["Chest Wall Resection"] = [
    {"question": "The sternum develops from lateral plate mesoderm through sternal bar fusion. What congenital anomaly results from incomplete fusion?",
     "answer": "Sternal cleft (failure of midline sternal bar fusion). Complete sternal cleft exposes the heart and great vessels. Partial clefts present as a superior or inferior notch. This is distinct from pectus excavatum (overgrowth of costal cartilages). Understanding sternal embryology matters for chest wall resection because sternal tumors (chondrosarcoma being most common) require partial or total sternectomy with reconstruction using methyl methacrylate or titanium plates."},
    {"question": "What is the internal mammary artery and vein anatomy at each intercostal level, and why must it be controlled during chest wall resection?",
     "answer": "The internal mammary (internal thoracic) artery runs 1-2cm lateral to the sternal border, giving off anterior intercostal branches at each space. It bifurcates at the 6th intercostal space into the musculophrenic and superior epigastric arteries. The accompanying veins run alongside. During chest wall resection, each cut intercostal space requires identification and ligation of the IMA perforators anteriorly AND the posterior intercostal arteries from the aorta. Uncontrolled IMA branch bleeding causes rapid, hard-to-visualize retrosternal hemorrhage."},
    {"question": "What is the 'sandwich technique' for rigid chest wall reconstruction after resection, and when is it used?",
     "answer": "Two layers of polypropylene (Marlex) or PTFE (Gore-Tex) mesh with methyl methacrylate cement molded between them, creating a rigid prosthetic plate. Used for anterior/lateral defects >5cm or involving ≥3 ribs. The cement is applied while doughy and molded to match chest wall contour, then hardens exothermically. Posterior defects under the scapula may not need rigid reconstruction because the scapula provides mechanical stability. Modern titanium rib plating systems (STRATOS, MatrixRIB) are increasingly used as alternatives."},
    {"question": "What is radiation-induced chest wall sarcoma, and what makes it a unique surgical challenge?",
     "answer": "Post-radiation sarcomas develop 5-30 years after chest wall irradiation (most commonly after breast cancer RT). Most are high-grade undifferentiated pleomorphic sarcomas or osteosarcomas. They require wide (≥4cm) en bloc resection through irradiated tissue with poor vascularity. Wound healing is compromised — local muscle flaps (latissimus, pectoralis) are often in the radiation field and unreliable. Pedicled omental flaps (reliable blood supply from gastroepiploic artery) or free flaps may be required. 5-year survival: 30-40%."},
    {"question": "What is the 'chimney' thoracostomy technique for infected chest wall prostheses after resection?",
     "answer": "When prosthetic chest wall reconstruction becomes infected (5-10% — higher with mesh, especially after radiation), the infected prosthetic must be removed. If the soft tissue cannot be closed primarily, an open window thoracostomy (Eloesser flap or modified Clagett procedure) creates a permanent or staged opening for packing and drainage. Negative-pressure wound therapy (wound VAC) applied to the chest wall defect accelerates granulation tissue formation, allowing delayed flap closure or secondary intention healing."}
]

Q5["Diaphragmatic Plication"] = [
    {"question": "The diaphragm develops from four embryologic sources. What are they, and which corresponds to the central tendon?",
     "answer": "1) Septum transversum (central tendon — the main embryologic component), 2) Pleuroperitoneal membranes (close the pleuroperitoneal canals), 3) Dorsal mesentery of the esophagus (contributes the crura), 4) Body wall mesoderm (peripheral muscular rim from cervical myotomes C3-C5 — this is why the phrenic nerve descends from C3-C5 to innervate a thoracoabdominal structure). Eventration occurs when the muscular component fails to develop properly."},
    {"question": "What is the 'sniff test' for diagnosing diaphragmatic paralysis, and what does a positive test look like?",
     "answer": "Fluoroscopic or ultrasound observation during quick inspiratory sniff through the nose. Normal: both hemidiaphragms descend with sniffing. Positive test (paradoxical motion): the paralyzed hemidiaphragm rises ≥2cm during sniffing (pulled upward by the negative intrathoracic pressure generated by the functioning contralateral hemidiaphragm). Ultrasound is now preferred over fluoroscopy (no radiation) — M-mode ultrasound measures diaphragmatic excursion quantitatively. A difference of >50% between sides confirms unilateral paralysis."},
    {"question": "What are the inferior phrenic arteries, and how are they preserved during diaphragmatic plication?",
     "answer": "The right and left inferior phrenic arteries are typically the first branches of the abdominal aorta (or may arise from the celiac trunk). They supply the majority of the diaphragmatic dome, running along the inferior surface and branching radially. During VATS plication (approaching from above), these arteries are not directly visualized — the plication sutures pass through the full thickness of the attenuated diaphragm but should avoid the central hiatal region where the inferior phrenic vessels are largest to prevent hemorrhage into the abdomen."},
    {"question": "What is the expected FEV1 improvement after plication, and which patients benefit most versus least?",
     "answer": "Mean FEV1 improvement: 15-20%. FVC improvement: 20-25%. Patients who benefit most: symptomatic dyspnea on exertion with documented paradoxical motion, BMI <35, and no underlying lung disease. Patients who benefit least: bilateral phrenic nerve paralysis (both diaphragms paralyzed — bilateral plication has higher morbidity and limited benefit; these patients may need long-term ventilatory support), morbid obesity (persistent restriction), and advanced COPD (dyspnea is multifactorial)."},
    {"question": "What is the long-term durability of diaphragmatic plication, and what causes plication failure?",
     "answer": "Long-term success: >85% maintain symptomatic improvement at 5-10 years. Plication failure (15%): suture pullthrough (most common — the attenuated diaphragm muscle is thin and may not hold sutures), progressive neuromuscular disease (ALS, myasthenia), and recurrent phrenic nerve injury. Pledgets or felt strips reinforce the plication sutures in severely attenuated tissue. Re-do plication is technically feasible but has lower success rates (60-70%) due to scarring and tissue quality."}
]

Q5["Lung Volume Reduction Surgery"] = [
    {"question": "What is the embryologic basis of the paraseptal (distal acinar) distribution of emphysema targeted by LVRS?",
     "answer": "The distal acinus develops last during fetal alveolarization (continuing postnatally until age 8). The alveolar septa in the lung periphery are thinnest and most susceptible to protease destruction (alpha-1 antitrypsin deficiency) and oxidant damage (smoking). Paraseptal/upper-lobe emphysema creates large subpleural bullae with destroyed alveolar walls but preserved central airways — this 'target area' of non-functional lung is what LVRS resects, decompressing adjacent relatively preserved lung tissue."},
    {"question": "What are the mediastinal shift dynamics after unilateral LVRS, and how does bilateral LVRS differ technically?",
     "answer": "After unilateral LVRS, the mediastinum may shift toward the operated side as the resected lung occupies less volume. Bilateral LVRS (performed via median sternotomy or staged bilateral VATS) balances the volume reduction symmetrically. The NETT trial used bilateral LVRS for upper-lobe-predominant disease. Current practice prefers staged bilateral VATS (4-6 weeks apart) to reduce the perioperative risk of simultaneous bilateral surgery and allow assessment of first-side response before committing to the second side."},
    {"question": "What buttressing materials are used on LVRS staple lines, and what is the evidence for each?",
     "answer": "Bovine pericardium (Peristrips): most commonly used, reduces air leak duration from 10-14 days to 5-7 days. ePTFE (Gore Seamguard): synthetic, non-absorbable, equivalent to bovine pericardium. PGA/TMC (Biodesign, absorbable): newer option. Without buttressing, prolonged air leak (>7 days) occurs in 45-50% of LVRS patients. With buttressing, this drops to 20-25%. The air leak is the #1 source of morbidity — it increases hospital stay, chest tube duration, and infection risk."},
    {"question": "What is the NETT high-risk subgroup that should NOT undergo LVRS?",
     "answer": "FEV1 ≤20% predicted AND either homogeneous emphysema distribution OR DLCO ≤20% predicted. This subgroup had 30-day mortality of 16% with LVRS (versus 0% medical therapy). These patients are candidates for endobronchial valve therapy or lung transplantation instead. The NETT trial's most important contribution was defining who should NOT have LVRS — saving lives through patient exclusion rather than inclusion."},
    {"question": "What is the mechanism of action of endobronchial valves (Zephyr), and what anatomic prerequisite must be confirmed before placement?",
     "answer": "Zephyr valves are one-way silicone duckbill valves placed bronchoscopically in segmental bronchi of the target lobe. They allow air and mucus OUT during exhalation but prevent air entry during inhalation → progressive lobar atelectasis (volume reduction without surgery). The prerequisite: absence of collateral ventilation to the target lobe, confirmed by the Chartis catheter (measures airflow through interlobar fissure). Intact fissures predict success. If collateral ventilation exists, the target lobe won't collapse."}
]

Q5["VATS Wedge Resection"] = [
    {"question": "At what week of fetal development does the lung begin to form from the foregut endoderm, and how does this relate to the visceral-parietal pleural distinction?",
     "answer": "The respiratory diverticulum (lung bud) appears at week 4 from the ventral foregut endoderm. The lung parenchyma and visceral pleura derive from splanchnic mesoderm surrounding the developing bronchial buds (visceral afferent innervation via vagus — dull, poorly localized pain). The parietal pleura derives from somatic mesoderm of the body wall (somatic innervation via intercostal nerves — sharp, well-localized pain). This is why pleuritic chest pain from parietal pleural irritation is sharp and positional."},
    {"question": "What are the intersegmental planes, and why does wedge resection intentionally ignore them?",
     "answer": "Each bronchopulmonary segment is a cone-shaped functional unit with its own bronchus, artery, and vein, separated from adjacent segments by connective tissue intersegmental planes. Segmentectomy follows these planes (identified by selective segmental inflation/deflation). Wedge resection intentionally crosses segmental boundaries — stapling across lung parenchyma regardless of segmental anatomy — because the goal is margin around a peripheral nodule, not anatomic completeness. This makes wedge faster and simpler but provides no lymph node sampling."},
    {"question": "What is the pulmonary arterial anatomy at the level of a typical upper lobe wedge resection, and why is it rarely at risk?",
     "answer": "The pulmonary arteries run centrally alongside the bronchi, deep within the lung parenchyma at the hilum. A peripheral wedge resection stays in the outer 1-3cm of lung — well away from named pulmonary arterial branches. The stapler compresses small peripheral arterioles and venules without encountering named vessels. This is why wedge resection has minimal blood loss (<50mL typically). The only vascular risk is from adhesions between the visceral and parietal pleura that may contain intercostal artery branches."},
    {"question": "What is the significance of the JCOG0802 trial for wedge resection of small lung cancers?",
     "answer": "JCOG0802/WJOG4607L (2022, Lancet): for peripheral NSCLC ≤2cm with a consolidation-to-tumor ratio >0.5, segmentectomy (not wedge) was non-inferior to lobectomy for 5-year OS (94.3% vs 91.1% — segmentectomy was actually superior). However, wedge resection was NOT studied as the sublobar arm — it was segmentectomy. Wedge resection remains appropriate for diagnosis (nodule of unknown etiology), metastasectomy, and patients with insufficient pulmonary reserve for segmentectomy or lobectomy."},
    {"question": "What is the protocol for intraoperative frozen section during VATS wedge resection of a new lung nodule?",
     "answer": "The specimen is immediately sent for frozen section (results in 15-20 minutes). If benign (granuloma, hamartoma): wedge resection is curative, case complete. If primary lung cancer: proceed to lobectomy or segmentectomy with mediastinal lymph node sampling/dissection in the same anesthetic (if the patient has adequate reserve). If metastatic carcinoma: wedge resection with adequate margins is sufficient, no further resection needed. The margin is re-assessed — if <1cm or less than the nodule diameter, re-excise before completing."}
]

# ============================================================
# GYN
# ============================================================

# Vulvectomy is already defined above

# ============================================================
# PRINT SUMMARY
# ============================================================
if __name__ == '__main__':
    print(f"Q5 loaded: {len(Q5)} procedures")
    for name, qs in Q5.items():
        print(f"  {name}: {len(qs)} questions")
