// Specialty data with top diagnoses and procedures
const SPECIALTIES = {
    "General Surgery": {
        diagnoses: [
            "Acute Appendicitis", "Acute Cholecystitis", "Cholelithiasis", "Inguinal Hernia",
            "Ventral Hernia", "Umbilical Hernia", "Small Bowel Obstruction", "Large Bowel Obstruction",
            "Colon Cancer", "Rectal Cancer", "Breast Cancer", "Breast Mass/Lump",
            "Diverticulitis", "Perianal Abscess", "Pilonidal Cyst", "Hemorrhoids",
            "Melanoma", "Soft Tissue Sarcoma", "Thyroid Nodule", "Thyroid Cancer",
            "Hyperparathyroidism", "Adrenal Mass", "Gastric Cancer", "GERD/Hiatal Hernia",
            "Morbid Obesity", "GI Bleed - Upper", "GI Bleed - Lower", "Peptic Ulcer Disease",
            "Pancreatitis - Acute", "Pancreatitis - Chronic", "Pancreatic Cancer",
            "Liver Mass/HCC", "Splenic Laceration", "Bowel Perforation", "Mesenteric Ischemia",
            "Necrotizing Fasciitis", "Abscess - Skin/Soft Tissue", "Wound Infection/SSI",
            "Enterocutaneous Fistula", "Short Bowel Syndrome", "Achalasia",
            "Zenker Diverticulum", "Anal Fissure", "Rectal Prolapse", "Volvulus",
            "Intussusception", "Meckel Diverticulum", "Appendiceal Neoplasm",
            "Gallbladder Cancer", "Bile Duct Injury", "Cholangiocarcinoma",
            "Lymph Node Biopsy", "Port Placement", "Feeding Tube Placement",
            "Trauma - Blunt Abdominal", "Trauma - Penetrating", "Trauma - Thoracic",
            "Rib Fractures", "Pneumothorax", "Hemothorax", "Splenic Rupture",
            "Liver Laceration", "Bowel Injury", "Diaphragm Injury",
            "Compartment Syndrome", "Amputation", "Surgical Site Infection",
            "DVT/PE Prophylaxis", "Wound Dehiscence", "Anastomotic Leak",
            "Sepsis - Surgical Source", "ARDS", "Multi-Organ Failure",
            "Tracheostomy Placement", "Central Line Placement", "Chest Tube Placement",
            "Ventilator Management", "TPN/Nutrition Support", "Surgical Consent",
            "Goals of Care Discussion", "Palliative Care Consultation"
        ],
        procedures: [

            "Hospital Visit (Inpatient Rounding)",
            "Office Visit (Outpatient)",
            "Emergency Department Visit",
            "Urgent Care Visit",
            "ICU Visit/Rounding",
            "Pre-operative Visit",
            "Post-operative Visit",
            "Consultation (New Patient)",
            "Follow-up Visit",
            "Admission H&P",
            "Discharge Planning",
            "Telehealth Visit",
            "Bedside Procedure",
            "Patient Education/Counseling",
            "Multidisciplinary Rounds",
            "Morning Rounds",
            "Night Float/Cross-Cover",
            "Rapid Response",
            "Code Blue/Resuscitation",
            "Goals of Care Discussion",
            "Family Meeting",
            "Death Pronouncement",
            "Transfer of Care",
            "Handoff (Sign-out)",
            "Clinic/Ambulatory Visit",
            "Observation Stay",
            "Same-Day Surgery Visit",
            "Labor & Delivery Visit",
            "Newborn Nursery Visit",
            "Psychiatric Evaluation",
            "Wound Check/Follow-up",
            // Specialty-specific procedures below
            "Laparoscopic Cholecystectomy", "Open Cholecystectomy",
            "Laparoscopic Appendectomy", "Open Appendectomy",
            "Inguinal Hernia Repair", "Laparoscopic Inguinal Hernia Repair",
            "Ventral Hernia Repair", "Laparoscopic Ventral Hernia Repair",
            "Umbilical Hernia Repair", "Incisional Hernia Repair",
            "Right Hemicolectomy", "Left Hemicolectomy", "Sigmoid Colectomy",
            "Lap Colectomy with Anastomosis", "Total Colectomy",
            "Small Bowel Resection", "Lysis of Adhesions",
            "Exploratory Laparotomy", "Splenectomy", "Liver Repair",
            "Partial Mastectomy (Lumpectomy)", "Simple Mastectomy",
            "Modified Radical Mastectomy", "Sentinel Lymph Node Biopsy",
            "Total Thyroidectomy", "Thyroid Lobectomy", "Parathyroidectomy",
            "Laparoscopic Adrenalectomy", "Laparoscopic Gastric Bypass (RYGB)",
            "Laparoscopic Sleeve Gastrectomy", "Nissen Fundoplication",
            "EGD with Biopsy", "Colonoscopy", "PEG Tube Placement",
            "Central Venous Catheter", "Chest Tube Insertion", "Tracheostomy",
            "Wound Debridement", "I&D Abscess", "Skin Graft",
            "Hemorrhoidectomy", "Pilonidal Cystectomy", "Port Placement",
            "Feeding Jejunostomy", "Damage Control Laparotomy",
            "Fem-Pop Bypass", "Carotid Endarterectomy", "AV Fistula Creation",
            "Amputation (Below Knee)", "Amputation (Above Knee)"
        ]
    },
    "Internal Medicine": {
        diagnoses: [
            "Chest Pain/ACS", "Acute MI (STEMI)", "Acute MI (NSTEMI)", "Unstable Angina",
            "Heart Failure - Acute", "Heart Failure - Chronic", "Atrial Fibrillation",
            "Atrial Flutter", "SVT", "Ventricular Tachycardia", "Hypertensive Emergency",
            "Hypertension - Uncontrolled", "Aortic Stenosis", "Mitral Regurgitation",
            "Endocarditis", "Pericarditis", "Pericardial Effusion",
            "Pneumonia - Community Acquired", "Pneumonia - Hospital Acquired",
            "Pneumonia - Aspiration", "COPD Exacerbation", "Asthma Exacerbation",
            "Pulmonary Embolism", "DVT", "Pleural Effusion", "Pneumothorax",
            "Respiratory Failure - Acute", "ARDS", "Pulmonary Fibrosis",
            "Sepsis", "Septic Shock", "Bacteremia", "UTI/Pyelonephritis",
            "Cellulitis", "Osteomyelitis", "Meningitis", "C. Diff Colitis",
            "HIV/AIDS", "COVID-19", "Influenza",
            "AKI - Prerenal", "AKI - Intrinsic", "AKI - Postrenal",
            "CKD Stage 3-5", "Hyperkalemia", "Hyponatremia", "Hypernatremia",
            "Metabolic Acidosis", "Metabolic Alkalosis", "Rhabdomyolysis",
            "DKA", "HHS", "Type 2 Diabetes - Uncontrolled", "Type 1 Diabetes",
            "Hypothyroidism", "Hyperthyroidism/Graves", "Adrenal Insufficiency",
            "Cirrhosis", "Hepatic Encephalopathy", "Variceal Bleeding",
            "Acute Hepatitis", "GI Bleed - Upper", "GI Bleed - Lower",
            "Pancreatitis - Acute", "IBD Flare (Crohn/UC)", "C. Diff Colitis",
            "SLE Flare", "Rheumatoid Arthritis", "Gout Flare", "Vasculitis",
            "Anemia - Iron Deficiency", "Anemia - B12/Folate", "Sickle Cell Crisis",
            "Thrombocytopenia", "DIC", "TTP/HUS", "Leukemia", "Lymphoma",
            "Lung Cancer", "Pancreatic Cancer", "Colon Cancer",
            "Stroke - Ischemic", "Stroke - Hemorrhagic", "Seizure",
            "Delirium", "Alcohol Withdrawal", "Opioid Overdose",
            "Syncope", "Falls - Elderly", "Pressure Ulcer",
            "Palliative Care", "Goals of Care Discussion", "Code Status Discussion"
        ],
        procedures: [

            "Hospital Visit (Inpatient Rounding)",
            "Office Visit (Outpatient)",
            "Emergency Department Visit",
            "Urgent Care Visit",
            "ICU Visit/Rounding",
            "Pre-operative Visit",
            "Post-operative Visit",
            "Consultation (New Patient)",
            "Follow-up Visit",
            "Admission H&P",
            "Discharge Planning",
            "Telehealth Visit",
            "Bedside Procedure",
            "Patient Education/Counseling",
            "Multidisciplinary Rounds",
            "Morning Rounds",
            "Night Float/Cross-Cover",
            "Rapid Response",
            "Code Blue/Resuscitation",
            "Goals of Care Discussion",
            "Family Meeting",
            "Death Pronouncement",
            "Transfer of Care",
            "Handoff (Sign-out)",
            "Clinic/Ambulatory Visit",
            "Observation Stay",
            "Same-Day Surgery Visit",
            "Labor & Delivery Visit",
            "Newborn Nursery Visit",
            "Psychiatric Evaluation",
            "Wound Check/Follow-up",
            // Specialty-specific procedures below
            "History & Physical", "Admission Orders", "Discharge Summary",
            "Arterial Blood Gas Interpretation", "ECG Interpretation",
            "Chest X-Ray Interpretation", "Paracentesis", "Thoracentesis",
            "Lumbar Puncture", "Central Line Placement", "Arterial Line",
            "Intubation", "Joint Aspiration", "Skin Biopsy",
            "NG Tube Placement", "Foley Catheter", "Wound Care",
            "Code Blue/ACLS", "Rapid Response", "Informed Consent",
            "Death Pronouncement", "Family Meeting"
        ]
    },
    "Family Medicine": {
        diagnoses: [
            "Hypertension", "Type 2 Diabetes", "Hyperlipidemia", "Obesity",
            "Metabolic Syndrome", "Coronary Artery Disease", "Heart Failure",
            "Atrial Fibrillation", "COPD", "Asthma",
            "Upper Respiratory Infection", "Sinusitis", "Otitis Media",
            "Strep Pharyngitis", "Bronchitis", "Pneumonia", "Influenza", "COVID-19",
            "UTI", "Pyelonephritis", "Vaginitis", "STI Screening",
            "Low Back Pain", "Osteoarthritis", "Rheumatoid Arthritis",
            "Gout", "Fibromyalgia", "Carpal Tunnel Syndrome",
            "Headache - Tension", "Headache - Migraine", "Vertigo/BPPV",
            "Depression", "Anxiety", "ADHD", "Insomnia", "PTSD",
            "Substance Use Disorder", "Alcohol Use Disorder", "Tobacco Cessation",
            "Hypothyroidism", "Hyperthyroidism", "Osteoporosis",
            "Anemia - Iron Deficiency", "Vitamin D Deficiency", "B12 Deficiency",
            "Eczema/Dermatitis", "Psoriasis", "Acne", "Skin Cancer Screening",
            "Allergic Rhinitis", "Food Allergy", "Drug Allergy",
            "Well Child Visit", "Well Woman Exam", "Annual Physical",
            "Preventive Screening (age appropriate)", "Immunizations",
            "Prenatal Care", "Postpartum Visit", "Contraception Counseling",
            "Abnormal Pap Smear", "Breast Mass", "Prostate Cancer Screening",
            "Colon Cancer Screening", "Lung Cancer Screening",
            "Chronic Pain Management", "Opioid Management",
            "Obesity/Weight Management", "Prediabetes Counseling",
            "CHF Follow-up", "COPD Follow-up", "Diabetes Follow-up",
            "Laceration Repair", "Abscess I&D", "Skin Tag Removal",
            "Wart Treatment", "Ingrown Toenail", "Musculoskeletal Injury",
            "Sprain/Strain", "Fracture Management", "Sports Physical",
            "ADHD Follow-up", "Depression Follow-up", "Anxiety Follow-up",
            "Geriatric Assessment", "Falls Risk Assessment", "Cognitive Screening",
            "Advance Directive Discussion", "Hospice Referral",
            "Social Determinants of Health", "Care Coordination"
        ],
        procedures: [

            "Hospital Visit (Inpatient Rounding)",
            "Office Visit (Outpatient)",
            "Emergency Department Visit",
            "Urgent Care Visit",
            "ICU Visit/Rounding",
            "Pre-operative Visit",
            "Post-operative Visit",
            "Consultation (New Patient)",
            "Follow-up Visit",
            "Admission H&P",
            "Discharge Planning",
            "Telehealth Visit",
            "Bedside Procedure",
            "Patient Education/Counseling",
            "Multidisciplinary Rounds",
            "Morning Rounds",
            "Night Float/Cross-Cover",
            "Rapid Response",
            "Code Blue/Resuscitation",
            "Goals of Care Discussion",
            "Family Meeting",
            "Death Pronouncement",
            "Transfer of Care",
            "Handoff (Sign-out)",
            "Clinic/Ambulatory Visit",
            "Observation Stay",
            "Same-Day Surgery Visit",
            "Labor & Delivery Visit",
            "Newborn Nursery Visit",
            "Psychiatric Evaluation",
            "Wound Check/Follow-up",
            // Specialty-specific procedures below
            "History & Physical", "Well Visit", "Annual Exam",
            "Pap Smear", "IUD Insertion", "IUD Removal", "Nexplanon Insertion",
            "Joint Injection", "Trigger Point Injection",
            "Laceration Repair", "I&D Abscess", "Skin Biopsy",
            "Skin Tag/Lesion Removal", "Cryotherapy (Wart)",
            "Toenail Removal", "Ear Lavage", "Foreign Body Removal",
            "Splinting/Casting", "Spirometry", "ECG Interpretation",
            "Newborn Exam", "Circumcision", "Colposcopy"
        ]
    },
    "Pediatrics": {
        diagnoses: [
            "Well Child Visit (Newborn)", "Well Child Visit (Infant)", "Well Child Visit (Toddler)",
            "Well Child Visit (School Age)", "Well Child Visit (Adolescent)",
            "Immunization Visit", "Developmental Delay", "Failure to Thrive",
            "Neonatal Jaundice", "Neonatal Sepsis", "Prematurity",
            "Respiratory Distress - Newborn", "Bronchiolitis (RSV)",
            "Croup", "Asthma - Pediatric", "Pneumonia - Pediatric",
            "Upper Respiratory Infection", "Otitis Media", "Strep Pharyngitis",
            "Hand Foot and Mouth Disease", "Fifth Disease", "Roseola",
            "Gastroenteritis - Viral", "Dehydration", "Constipation - Pediatric",
            "Appendicitis - Pediatric", "Intussusception", "Pyloric Stenosis",
            "GERD - Infant", "Colic", "Food Allergy",
            "Eczema/Atopic Dermatitis", "Diaper Rash", "Impetigo",
            "Kawasaki Disease", "Henoch-Schonlein Purpura",
            "UTI - Pediatric", "Enuresis", "Vesicoureteral Reflux",
            "Febrile Seizure", "Epilepsy - Pediatric", "ADHD",
            "Autism Spectrum Disorder", "Anxiety - Pediatric", "Depression - Pediatric",
            "Type 1 Diabetes", "Diabetic Ketoacidosis - Pediatric",
            "Growth Hormone Deficiency", "Precocious Puberty",
            "Sickle Cell Disease", "ITP", "Leukemia - Pediatric",
            "Fracture - Pediatric", "Child Abuse/NAT", "Foreign Body Ingestion",
            "Poisoning/Ingestion", "Drowning", "Head Injury - Pediatric",
            "Congenital Heart Disease", "Heart Murmur Evaluation",
            "Obesity - Pediatric", "Sports Physical",
            "Lead Screening", "Vision/Hearing Screening",
            "Adolescent Health (Contraception, STI)", "Eating Disorder",
            "Suicidal Ideation - Adolescent"
        ],
        procedures: [

            "Hospital Visit (Inpatient Rounding)",
            "Office Visit (Outpatient)",
            "Emergency Department Visit",
            "Urgent Care Visit",
            "ICU Visit/Rounding",
            "Pre-operative Visit",
            "Post-operative Visit",
            "Consultation (New Patient)",
            "Follow-up Visit",
            "Admission H&P",
            "Discharge Planning",
            "Telehealth Visit",
            "Bedside Procedure",
            "Patient Education/Counseling",
            "Multidisciplinary Rounds",
            "Morning Rounds",
            "Night Float/Cross-Cover",
            "Rapid Response",
            "Code Blue/Resuscitation",
            "Goals of Care Discussion",
            "Family Meeting",
            "Death Pronouncement",
            "Transfer of Care",
            "Handoff (Sign-out)",
            "Clinic/Ambulatory Visit",
            "Observation Stay",
            "Same-Day Surgery Visit",
            "Labor & Delivery Visit",
            "Newborn Nursery Visit",
            "Psychiatric Evaluation",
            "Wound Check/Follow-up",
            // Specialty-specific procedures below
            "Newborn Exam", "Well Child Exam", "Developmental Screening",
            "Immunization Administration", "Vision/Hearing Screen",
            "Lead Screening", "Circumcision", "Frenotomy",
            "Foreign Body Removal", "Laceration Repair",
            "Lumbar Puncture - Pediatric", "IV Placement - Pediatric",
            "NG Tube - Pediatric", "Bladder Catheterization",
            "Rapid Strep Test", "Flu Test", "Urinalysis"
        ]
    },
    "OB/GYN": {
        diagnoses: [
            "Normal Pregnancy", "Prenatal Visit (1st Trimester)", "Prenatal Visit (2nd Trimester)",
            "Prenatal Visit (3rd Trimester)", "Gestational Diabetes", "Gestational Hypertension",
            "Preeclampsia", "Eclampsia", "HELLP Syndrome",
            "Placenta Previa", "Placental Abruption", "Preterm Labor",
            "PPROM", "Cervical Insufficiency", "Ectopic Pregnancy",
            "Miscarriage/SAB", "Hyperemesis Gravidarum", "Rh Isoimmunization",
            "Group B Strep", "Chorioamnionitis",
            "Normal Spontaneous Vaginal Delivery", "Cesarean Section",
            "Vacuum/Forceps Delivery", "Postpartum Hemorrhage",
            "Postpartum Depression", "Postpartum Preeclampsia",
            "Abnormal Uterine Bleeding", "Menorrhagia", "Dysmenorrhea",
            "Amenorrhea", "PCOS", "Endometriosis", "Fibroids (Leiomyoma)",
            "Ovarian Cyst", "Ovarian Torsion", "Ovarian Cancer",
            "Cervical Cancer", "Endometrial Cancer", "Abnormal Pap Smear",
            "Cervical Dysplasia (CIN)", "HPV",
            "Pelvic Inflammatory Disease", "Vaginitis", "Vulvovaginitis",
            "STI (Chlamydia, Gonorrhea, Syphilis, HSV)",
            "Urinary Incontinence", "Pelvic Organ Prolapse",
            "Infertility", "Contraception Counseling", "IUD Complications",
            "Menopause Management", "Osteoporosis - Postmenopausal",
            "Breast Mass", "Breast Cancer Screening",
            "Sexual Assault Exam", "Domestic Violence Screening"
        ],
        procedures: [

            "Hospital Visit (Inpatient Rounding)",
            "Office Visit (Outpatient)",
            "Emergency Department Visit",
            "Urgent Care Visit",
            "ICU Visit/Rounding",
            "Pre-operative Visit",
            "Post-operative Visit",
            "Consultation (New Patient)",
            "Follow-up Visit",
            "Admission H&P",
            "Discharge Planning",
            "Telehealth Visit",
            "Bedside Procedure",
            "Patient Education/Counseling",
            "Multidisciplinary Rounds",
            "Morning Rounds",
            "Night Float/Cross-Cover",
            "Rapid Response",
            "Code Blue/Resuscitation",
            "Goals of Care Discussion",
            "Family Meeting",
            "Death Pronouncement",
            "Transfer of Care",
            "Handoff (Sign-out)",
            "Clinic/Ambulatory Visit",
            "Observation Stay",
            "Same-Day Surgery Visit",
            "Labor & Delivery Visit",
            "Newborn Nursery Visit",
            "Psychiatric Evaluation",
            "Wound Check/Follow-up",
            // Specialty-specific procedures below
            "Prenatal Visit", "Leopold Maneuvers", "Fetal Heart Tone Assessment",
            "NST Interpretation", "BPP Interpretation", "Ultrasound (OB)",
            "Normal Vaginal Delivery", "Cesarean Section (Assist)",
            "Vacuum Delivery", "Forceps Delivery",
            "Laceration Repair (Perineal)", "Episiotomy Repair",
            "Manual Placenta Removal", "Postpartum Hemorrhage Management",
            "Pap Smear", "Colposcopy", "LEEP/Cone Biopsy",
            "IUD Insertion", "IUD Removal", "Nexplanon Insertion/Removal",
            "Endometrial Biopsy", "Hysteroscopy",
            "Laparoscopy (Diagnostic)", "Laparoscopic Cystectomy",
            "Hysterectomy (Assist)", "D&C", "Cerclage",
            "Amniocentesis", "Ultrasound (Gyn)",
            "Sexual Assault Exam (SANE)"
        ]
    },
    "Emergency Medicine": {
        diagnoses: [
            "Chest Pain - ACS Rule Out", "STEMI", "NSTEMI", "Aortic Dissection",
            "Pulmonary Embolism", "Pneumothorax - Tension", "Pneumothorax - Simple",
            "Cardiac Arrest", "SVT", "Atrial Fibrillation (Acute)", "Heart Failure - Acute",
            "Stroke - Ischemic", "Stroke - Hemorrhagic", "TIA",
            "Seizure", "Status Epilepticus", "Meningitis", "Encephalitis",
            "Headache - Thunderclap", "Subarachnoid Hemorrhage",
            "Sepsis", "Septic Shock", "Anaphylaxis", "Allergic Reaction",
            "Asthma Exacerbation", "COPD Exacerbation", "Respiratory Failure",
            "Pneumonia", "Upper Airway Obstruction",
            "Abdominal Pain - Undifferentiated", "Appendicitis", "Cholecystitis",
            "Diverticulitis", "Small Bowel Obstruction", "GI Bleed",
            "Pancreatitis", "Ectopic Pregnancy", "Ovarian Torsion",
            "Testicular Torsion", "Kidney Stone/Renal Colic",
            "UTI/Pyelonephritis", "Urinary Retention",
            "DKA", "HHS", "Hypoglycemia", "Thyroid Storm",
            "Adrenal Crisis", "Hyperkalemia", "Hyponatremia",
            "Trauma - Blunt (MVC)", "Trauma - Penetrating (GSW/Stab)",
            "Trauma - Fall", "Trauma - Pediatric", "Head Injury/TBI",
            "C-Spine Injury", "Spinal Cord Injury", "Pelvic Fracture",
            "Long Bone Fracture", "Open Fracture", "Dislocation",
            "Compartment Syndrome", "Burns", "Drowning",
            "Laceration", "Dog Bite", "Human Bite", "Abscess",
            "Cellulitis", "Necrotizing Fasciitis",
            "Overdose - Opioid", "Overdose - Acetaminophen", "Overdose - Benzodiazepine",
            "Alcohol Intoxication", "Alcohol Withdrawal/DTs",
            "Suicidal Ideation", "Psychosis - Acute", "Agitation",
            "DVT", "Ischemic Limb - Acute",
            "Ruptured AAA", "GI Foreign Body", "Airway Foreign Body",
            "Snake Bite", "Environmental Emergency (Heat/Cold)"
        ],
        procedures: [

            "Hospital Visit (Inpatient Rounding)",
            "Office Visit (Outpatient)",
            "Emergency Department Visit",
            "Urgent Care Visit",
            "ICU Visit/Rounding",
            "Pre-operative Visit",
            "Post-operative Visit",
            "Consultation (New Patient)",
            "Follow-up Visit",
            "Admission H&P",
            "Discharge Planning",
            "Telehealth Visit",
            "Bedside Procedure",
            "Patient Education/Counseling",
            "Multidisciplinary Rounds",
            "Morning Rounds",
            "Night Float/Cross-Cover",
            "Rapid Response",
            "Code Blue/Resuscitation",
            "Goals of Care Discussion",
            "Family Meeting",
            "Death Pronouncement",
            "Transfer of Care",
            "Handoff (Sign-out)",
            "Clinic/Ambulatory Visit",
            "Observation Stay",
            "Same-Day Surgery Visit",
            "Labor & Delivery Visit",
            "Newborn Nursery Visit",
            "Psychiatric Evaluation",
            "Wound Check/Follow-up",
            // Specialty-specific procedures below
            "Primary Survey (ATLS)", "Secondary Survey", "FAST Exam",
            "Intubation (RSI)", "Cricothyrotomy", "Bag-Valve Mask",
            "Chest Tube Insertion", "Needle Decompression",
            "Central Line Placement", "IO Access", "Arterial Line",
            "Lumbar Puncture", "Paracentesis", "Thoracentesis",
            "Pericardiocentesis", "Joint Aspiration",
            "Laceration Repair", "Wound Exploration", "I&D Abscess",
            "Fracture Reduction", "Dislocation Reduction", "Splinting",
            "Cardioversion", "Defibrillation", "Pacing (Transcutaneous)",
            "Sedation (Procedural)", "Nerve Block",
            "NG/OG Tube", "Foley Catheter", "Packing (Epistaxis/Wound)",
            "Slit Lamp Exam", "Foreign Body Removal (Eye/Ear/Nose)",
            "Sexual Assault Exam", "Code Blue/ACLS Lead",
            "Trauma Team Lead", "Rapid Sequence Intubation"
        ]
    },
    "Psychiatry": {
        diagnoses: [
            "Major Depressive Disorder", "Bipolar Disorder - Manic Episode",
            "Bipolar Disorder - Depressive Episode", "Generalized Anxiety Disorder",
            "Panic Disorder", "Social Anxiety Disorder", "PTSD",
            "OCD", "Adjustment Disorder",
            "Schizophrenia", "Schizoaffective Disorder", "Brief Psychotic Disorder",
            "Delusional Disorder", "Psychosis NOS",
            "Alcohol Use Disorder", "Opioid Use Disorder", "Cannabis Use Disorder",
            "Stimulant Use Disorder", "Alcohol Withdrawal", "Opioid Withdrawal",
            "Delirium Tremens",
            "ADHD - Adult", "ADHD - Child/Adolescent",
            "Autism Spectrum Disorder", "Intellectual Disability",
            "Anorexia Nervosa", "Bulimia Nervosa", "Binge Eating Disorder",
            "Borderline Personality Disorder", "Antisocial Personality Disorder",
            "Narcissistic Personality Disorder",
            "Suicidal Ideation", "Suicide Attempt", "Self-Harm/NSSI",
            "Homicidal Ideation", "Acute Agitation",
            "Insomnia", "Somatic Symptom Disorder", "Conversion Disorder",
            "Delirium", "Dementia/Neurocognitive Disorder",
            "Grief/Bereavement", "Malingering",
            "Involuntary Commitment Evaluation", "Capacity Evaluation",
            "Medication Management", "Therapy Referral"
        ],
        procedures: [

            "Hospital Visit (Inpatient Rounding)",
            "Office Visit (Outpatient)",
            "Emergency Department Visit",
            "Urgent Care Visit",
            "ICU Visit/Rounding",
            "Pre-operative Visit",
            "Post-operative Visit",
            "Consultation (New Patient)",
            "Follow-up Visit",
            "Admission H&P",
            "Discharge Planning",
            "Telehealth Visit",
            "Bedside Procedure",
            "Patient Education/Counseling",
            "Multidisciplinary Rounds",
            "Morning Rounds",
            "Night Float/Cross-Cover",
            "Rapid Response",
            "Code Blue/Resuscitation",
            "Goals of Care Discussion",
            "Family Meeting",
            "Death Pronouncement",
            "Transfer of Care",
            "Handoff (Sign-out)",
            "Clinic/Ambulatory Visit",
            "Observation Stay",
            "Same-Day Surgery Visit",
            "Labor & Delivery Visit",
            "Newborn Nursery Visit",
            "Psychiatric Evaluation",
            "Wound Check/Follow-up",
            // Specialty-specific procedures below
            "Psychiatric Evaluation", "Mental Status Exam",
            "Suicide Risk Assessment", "Safety Planning",
            "Involuntary Hold/Commitment", "Capacity Assessment",
            "Medication Initiation", "Medication Adjustment",
            "ECT Observation", "Group Therapy Observation",
            "Family Meeting", "Discharge Planning"
        ]
    },
    "Neurology": {
        diagnoses: [
            "Ischemic Stroke", "Hemorrhagic Stroke", "TIA",
            "Subarachnoid Hemorrhage", "Subdural Hematoma", "Epidural Hematoma",
            "Seizure - New Onset", "Epilepsy", "Status Epilepticus",
            "Migraine", "Tension Headache", "Cluster Headache",
            "Meningitis", "Encephalitis", "Brain Abscess",
            "Multiple Sclerosis", "Guillain-Barre Syndrome",
            "Myasthenia Gravis", "ALS", "Parkinson Disease",
            "Essential Tremor", "Huntington Disease",
            "Alzheimer Disease", "Vascular Dementia", "Lewy Body Dementia",
            "Normal Pressure Hydrocephalus",
            "Peripheral Neuropathy", "Carpal Tunnel Syndrome",
            "Bell Palsy", "Trigeminal Neuralgia",
            "Brain Tumor (Primary)", "Brain Metastasis",
            "Spinal Cord Compression", "Cauda Equina Syndrome",
            "Vertigo/BPPV", "Meniere Disease",
            "Syncope", "Concussion/mTBI",
            "Delirium", "Altered Mental Status"
        ],
        procedures: [

            "Hospital Visit (Inpatient Rounding)",
            "Office Visit (Outpatient)",
            "Emergency Department Visit",
            "Urgent Care Visit",
            "ICU Visit/Rounding",
            "Pre-operative Visit",
            "Post-operative Visit",
            "Consultation (New Patient)",
            "Follow-up Visit",
            "Admission H&P",
            "Discharge Planning",
            "Telehealth Visit",
            "Bedside Procedure",
            "Patient Education/Counseling",
            "Multidisciplinary Rounds",
            "Morning Rounds",
            "Night Float/Cross-Cover",
            "Rapid Response",
            "Code Blue/Resuscitation",
            "Goals of Care Discussion",
            "Family Meeting",
            "Death Pronouncement",
            "Transfer of Care",
            "Handoff (Sign-out)",
            "Clinic/Ambulatory Visit",
            "Observation Stay",
            "Same-Day Surgery Visit",
            "Labor & Delivery Visit",
            "Newborn Nursery Visit",
            "Psychiatric Evaluation",
            "Wound Check/Follow-up",
            // Specialty-specific procedures below
            "Neurological Exam", "Mental Status Exam",
            "Lumbar Puncture", "EEG Interpretation",
            "EMG/NCS Interpretation", "CT Head Interpretation",
            "MRI Brain Interpretation", "tPA Administration",
            "NIH Stroke Scale", "Glasgow Coma Scale"
        ]
    },
    "Nephrology": {
        diagnoses: [
            "AKI - Prerenal", "AKI - Intrinsic (ATN)", "AKI - Postrenal",
            "CKD Stage 1-2", "CKD Stage 3", "CKD Stage 4", "CKD Stage 5/ESRD",
            "Dialysis Initiation", "Hemodialysis Management", "Peritoneal Dialysis",
            "Kidney Transplant Follow-up",
            "Glomerulonephritis", "Nephrotic Syndrome", "Nephritic Syndrome",
            "IgA Nephropathy", "Membranous Nephropathy", "FSGS",
            "Minimal Change Disease", "Lupus Nephritis",
            "Diabetic Nephropathy", "Hypertensive Nephrosclerosis",
            "Polycystic Kidney Disease", "Renal Artery Stenosis",
            "Hyperkalemia", "Hypokalemia", "Hypernatremia", "Hyponatremia",
            "Metabolic Acidosis", "Metabolic Alkalosis",
            "Hypercalcemia", "Hypocalcemia", "Hyperphosphatemia",
            "Renal Tubular Acidosis", "Rhabdomyolysis",
            "Kidney Stones/Nephrolithiasis", "UTI/Pyelonephritis",
            "Urinary Tract Obstruction", "Contrast Nephropathy",
            "Drug-Induced Nephrotoxicity", "HUS/TTP"
        ],
        procedures: [

            "Hospital Visit (Inpatient Rounding)",
            "Office Visit (Outpatient)",
            "Emergency Department Visit",
            "Urgent Care Visit",
            "ICU Visit/Rounding",
            "Pre-operative Visit",
            "Post-operative Visit",
            "Consultation (New Patient)",
            "Follow-up Visit",
            "Admission H&P",
            "Discharge Planning",
            "Telehealth Visit",
            "Bedside Procedure",
            "Patient Education/Counseling",
            "Multidisciplinary Rounds",
            "Morning Rounds",
            "Night Float/Cross-Cover",
            "Rapid Response",
            "Code Blue/Resuscitation",
            "Goals of Care Discussion",
            "Family Meeting",
            "Death Pronouncement",
            "Transfer of Care",
            "Handoff (Sign-out)",
            "Clinic/Ambulatory Visit",
            "Observation Stay",
            "Same-Day Surgery Visit",
            "Labor & Delivery Visit",
            "Newborn Nursery Visit",
            "Psychiatric Evaluation",
            "Wound Check/Follow-up",
            // Specialty-specific procedures below
            "Urinalysis Interpretation", "Urine Electrolytes Interpretation",
            "Renal Biopsy (Observation)", "Dialysis Catheter Management",
            "AV Fistula Assessment", "Fluid/Electrolyte Management",
            "Acid-Base Interpretation", "Dialysis Prescription",
            "Kidney Transplant Evaluation"
        ]
    },
    "Cardiology": {
        diagnoses: [
            "Chest Pain - ACS Rule Out", "STEMI", "NSTEMI", "Unstable Angina",
            "Stable Angina", "Coronary Artery Disease",
            "Heart Failure - Systolic (HFrEF)", "Heart Failure - Diastolic (HFpEF)",
            "Heart Failure - Acute Decompensated",
            "Atrial Fibrillation", "Atrial Flutter", "SVT", "Ventricular Tachycardia",
            "Ventricular Fibrillation", "Bradycardia/Heart Block",
            "Sick Sinus Syndrome", "Long QT Syndrome", "WPW Syndrome",
            "Aortic Stenosis", "Aortic Regurgitation",
            "Mitral Stenosis", "Mitral Regurgitation", "Mitral Valve Prolapse",
            "Tricuspid Regurgitation", "Endocarditis",
            "Pericarditis", "Pericardial Effusion", "Cardiac Tamponade",
            "Myocarditis", "Cardiomyopathy - Dilated", "Cardiomyopathy - Hypertrophic",
            "Aortic Dissection", "Aortic Aneurysm",
            "Pulmonary Hypertension", "Cor Pulmonale",
            "Hypertension - Resistant", "Hypertensive Emergency",
            "Syncope - Cardiac", "Cardiac Arrest",
            "DVT/PE", "Peripheral Artery Disease",
            "Pre-op Cardiac Clearance", "Device Management (Pacemaker/ICD)"
        ],
        procedures: [

            "Hospital Visit (Inpatient Rounding)",
            "Office Visit (Outpatient)",
            "Emergency Department Visit",
            "Urgent Care Visit",
            "ICU Visit/Rounding",
            "Pre-operative Visit",
            "Post-operative Visit",
            "Consultation (New Patient)",
            "Follow-up Visit",
            "Admission H&P",
            "Discharge Planning",
            "Telehealth Visit",
            "Bedside Procedure",
            "Patient Education/Counseling",
            "Multidisciplinary Rounds",
            "Morning Rounds",
            "Night Float/Cross-Cover",
            "Rapid Response",
            "Code Blue/Resuscitation",
            "Goals of Care Discussion",
            "Family Meeting",
            "Death Pronouncement",
            "Transfer of Care",
            "Handoff (Sign-out)",
            "Clinic/Ambulatory Visit",
            "Observation Stay",
            "Same-Day Surgery Visit",
            "Labor & Delivery Visit",
            "Newborn Nursery Visit",
            "Psychiatric Evaluation",
            "Wound Check/Follow-up",
            // Specialty-specific procedures below
            "ECG Interpretation", "Echocardiogram Interpretation",
            "Stress Test Interpretation", "Cardiac Catheterization (Observation)",
            "PCI/Stent (Observation)", "Cardioversion",
            "Pacemaker/ICD Check", "Holter Monitor Interpretation",
            "Heart Failure Management", "Anticoagulation Management",
            "ACLS/Code Blue"
        ]
    }
};
